"""
Chunk runner for the BARK vs SKQD cluster study.

Reads params/param_grid.txt, slices it into N_CHUNKS equal parts, and
runs every experiment in this chunk sequentially.  The Slurm array job
sets CHUNK_IDX via $SLURM_ARRAY_TASK_ID.

Usage
-----
python run_chunk.py --chunk 0 --n_chunks 30 [--param_file params/param_grid.txt]
                    [--n_random_paths 100] [--seed 42] [--output_dir results]
"""

import argparse
import os
import sys
import time

# ---------------------------------------------------------------------------
# Add parent dir so run_experiment.run() can be imported directly
# ---------------------------------------------------------------------------
_HERE = os.path.dirname(os.path.abspath(__file__))
if _HERE not in sys.path:
    sys.path.insert(0, _HERE)

from run_experiment import run


def load_param_lines(param_file: str) -> list[tuple]:
    """Parse the parameter file into a list of (n_qubits, gs_sp, ham_sp, overlap, keep_states)."""
    lines = []
    with open(param_file) as f:
        for raw in f:
            raw = raw.strip()
            if not raw or raw.startswith("#"):
                continue
            parts = raw.split()
            if len(parts) != 5:
                raise ValueError(f"Bad param line (expected 5 fields): {raw!r}")
            n_qubits, gs_sp, ham_sp, overlap, keep_states = parts
            lines.append((int(n_qubits), float(gs_sp), float(ham_sp),
                          float(overlap), int(keep_states)))
    return lines


def chunk_slice(total: int, n_chunks: int, chunk_idx: int) -> range:
    """Return the index range for chunk_idx out of n_chunks over total items."""
    base, remainder = divmod(total, n_chunks)
    # First `remainder` chunks get one extra item
    start = chunk_idx * base + min(chunk_idx, remainder)
    stop  = start + base + (1 if chunk_idx < remainder else 0)
    return range(start, stop)


def main() -> None:
    p = argparse.ArgumentParser(
        description="Run one chunk of the parameter grid sequentially."
    )
    p.add_argument("--chunk",          type=int, required=True,
                   help="0-based index of this chunk.")
    p.add_argument("--n_chunks",       type=int, default=30,
                   help="Total number of chunks (= number of array jobs, default: 30).")
    p.add_argument("--param_file",     type=str, default="params/param_grid.txt",
                   help="Path to the parameter file generated by generate_jobs.py.")
    p.add_argument("--n_random_paths", type=int, default=100,
                   help="Random baseline paths per experiment (default: 100).")
    p.add_argument("--seed",           type=int, default=42,
                   help="Random seed (default: 42).")
    p.add_argument("--output_dir",     type=str, default="results",
                   help="Directory for output figures (default: results/).")
    args = p.parse_args()

    if args.chunk < 0 or args.chunk >= args.n_chunks:
        raise ValueError(f"--chunk must be in [0, {args.n_chunks - 1}]")

    # ------------------------------------------------------------------
    # Load and slice the parameter list
    # ------------------------------------------------------------------
    all_params = load_param_lines(args.param_file)
    total = len(all_params)
    my_range = chunk_slice(total, args.n_chunks, args.chunk)
    my_params = [all_params[i] for i in my_range]

    print(f"Chunk {args.chunk}/{args.n_chunks - 1}  —  "
          f"jobs {my_range.start}–{my_range.stop - 1} of {total - 1}  "
          f"({len(my_params)} experiments)", flush=True)
    print("=" * 60, flush=True)

    t_chunk_start = time.time()

    for local_idx, (n_qubits, gs_sp, ham_sp, overlap, keep_states) in enumerate(my_params):
        global_idx = my_range.start + local_idx
        print(f"\n[{local_idx + 1}/{len(my_params)}  global={global_idx}]", flush=True)

        # Skip if the output figure already exists (allows safe re-runs)
        fname = (
            f"nq{n_qubits}_gs{gs_sp:.2f}_ham{ham_sp:.2f}"
            f"_ov{overlap:.2f}_ks{keep_states:04d}_seed{args.seed}.png"
        )
        out_path = os.path.join(args.output_dir, fname)
        if os.path.exists(out_path):
            print(f"  Skipping (already exists): {fname}", flush=True)
            continue

        try:
            run(
                n_qubits=n_qubits,
                gs_sparsity=gs_sp,
                ham_sparsity=ham_sp,
                overlap=overlap,
                keep_states=keep_states,
                n_random_paths=args.n_random_paths,
                seed=args.seed,
                output_dir=args.output_dir,
            )
        except Exception as e:
            # Log the error and continue so one bad experiment doesn't kill the chunk
            print(f"  ERROR: {type(e).__name__}: {e}", flush=True)
            import traceback
            traceback.print_exc()
            print("  Continuing to next experiment.", flush=True)

    elapsed = time.time() - t_chunk_start
    print(f"\nChunk {args.chunk} finished in {elapsed/3600:.2f}h  "
          f"({elapsed:.0f}s, {len(my_params)} experiments).", flush=True)


if __name__ == "__main__":
    main()
